# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'
#' Hello to the world!
#'
#' This function returns something
#' @useDynLib rcppTestProject, .registration = TRUE
#' @importFrom Rcpp evalCpp
#' @export
rcpp_hello_world <- function() {
    .Call(`_rcppTestProject_rcpp_hello_world`)
}

